package query

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/anthropics/anthropic-sdk-go"
	"github.com/khaledmoayad/clawgo/internal/api"
)

// ToolUseSummarySystemPrompt is the system prompt used for generating
// tool use summaries via the small/fast model (Haiku). Matches Claude
// Code's TOOL_USE_SUMMARY_SYSTEM_PROMPT from toolUseSummaryGenerator.ts.
const ToolUseSummarySystemPrompt = `Write a short summary label describing what these tool calls accomplished. It appears as a single-line row in a mobile app and truncates around 30 characters, so think git-commit-subject, not sentence.

Keep the verb in past tense and the most distinctive noun. Drop articles, connectors, and long location context first.

Examples:
- Searched in auth/
- Fixed NPE in UserService
- Created signup endpoint
- Read config.json
- Ran failing tests`

// DefaultSmallFastModel is the default Haiku model used for summaries
// when no override is configured.
const DefaultSmallFastModel = "claude-haiku-3-5-20241022"

// maxSummaryInputLen caps the JSON representation of tool input/output
// included in the summary prompt to avoid sending oversized requests.
const maxSummaryInputLen = 300

// ToolUseSummaryResult holds the outcome of an async summary generation.
type ToolUseSummaryResult struct {
	// Summary is the generated summary text (empty on error).
	Summary string

	// Error is non-nil if summary generation failed. Failures are
	// non-critical and should be logged but not surfaced to the user.
	Error error
}

// toolInfo captures a single tool invocation for summary generation.
type toolInfo struct {
	Name   string
	Input  string
	Output string
}

// GenerateToolUseSummary starts an async summary generation for the
// most recent tool use batch in the conversation. It returns a channel
// that will receive exactly one *ToolUseSummaryResult when done.
//
// The summary is generated by sending the tool use/result pairs to the
// small/fast model (Haiku) with a concise system prompt. This matches
// Claude Code's generateToolUseSummary function.
//
// The caller should start this after tool execution and consume the
// result in a subsequent iteration (fire-and-forget pattern).
func GenerateToolUseSummary(ctx context.Context, client *api.Client, messages []api.Message, smallModel string) <-chan *ToolUseSummaryResult {
	ch := make(chan *ToolUseSummaryResult, 1)

	go func() {
		defer close(ch)

		result := &ToolUseSummaryResult{}

		// Extract recent tool use/result pairs
		tools := extractToolPairs(messages)
		if len(tools) == 0 {
			result.Summary = ""
			ch <- result
			return
		}

		// Build the user prompt
		var sb strings.Builder
		sb.WriteString("Tools completed:\n\n")
		for _, t := range tools {
			fmt.Fprintf(&sb, "Tool: %s\nInput: %s\nOutput: %s\n\n", t.Name, t.Input, t.Output)
		}
		sb.WriteString("Label:")

		// Use the small/fast model for summary generation
		model := smallModel
		if model == "" {
			model = DefaultSmallFastModel
		}

		// Build a minimal API request for summary generation
		req := anthropic.MessageNewParams{
			Model:    model,
			MaxTokens: 100, // Summaries are very short
			System: []anthropic.TextBlockParam{
				{Text: ToolUseSummarySystemPrompt},
			},
			Messages: []anthropic.MessageParam{
				{
					Role: "user",
					Content: []anthropic.ContentBlockParamUnion{
						anthropic.NewTextBlock(sb.String()),
					},
				},
			},
		}

		// Send the request (non-streaming for simplicity)
		msg, err := client.SDK.Messages.New(ctx, req)
		if err != nil {
			result.Error = fmt.Errorf("tool use summary generation failed: %w", err)
			ch <- result
			return
		}

		// Extract text from response
		var summary strings.Builder
		for _, block := range msg.Content {
			if block.Type == "text" {
				summary.WriteString(block.Text)
			}
		}

		result.Summary = strings.TrimSpace(summary.String())
		ch <- result
	}()

	return ch
}

// CreateToolUseSummaryMessage creates a user message containing the
// summary of tool use activity. This message is marked as meta/system
// content for context compression.
func CreateToolUseSummaryMessage(summary string) api.Message {
	return api.UserMessage("[Tool use summary: " + summary + "]")
}

// extractToolPairs scans messages from the end backwards to find the
// most recent batch of tool_use (in assistant messages) and their
// corresponding tool_result (in user messages).
func extractToolPairs(messages []api.Message) []toolInfo {
	if len(messages) == 0 {
		return nil
	}

	// Collect tool_use IDs from the last assistant message with tool_use blocks
	var toolUses []toolInfo
	toolUseIDs := make(map[string]int) // ID -> index in toolUses

	for i := len(messages) - 1; i >= 0; i-- {
		msg := messages[i]
		if msg.Role != "assistant" {
			continue
		}

		for _, cb := range msg.Content {
			if cb.Type != api.ContentToolUse {
				continue
			}

			info := toolInfo{
				Name:  cb.Name,
				Input: truncateJSON(cb.Input, maxSummaryInputLen),
			}
			toolUseIDs[cb.ID] = len(toolUses)
			toolUses = append(toolUses, info)
		}

		if len(toolUses) > 0 {
			break // Only process the most recent assistant message with tools
		}
	}

	if len(toolUses) == 0 {
		return nil
	}

	// Find corresponding tool_result blocks
	for _, msg := range messages {
		if msg.Role != "user" {
			continue
		}
		for _, cb := range msg.Content {
			if cb.Type != api.ContentToolResult {
				continue
			}
			if idx, ok := toolUseIDs[cb.ToolUseID]; ok {
				toolUses[idx].Output = truncateString(cb.Content, maxSummaryInputLen)
			}
		}
	}

	return toolUses
}

// truncateJSON converts a json.RawMessage to a string, truncating if needed.
func truncateJSON(data json.RawMessage, maxLen int) string {
	if data == nil {
		return "{}"
	}
	s := string(data)
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

// truncateString truncates a string to maxLen with an ellipsis marker.
func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
